//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingsman.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReports
    {
        public int Id { get; set; }
        public string ServiceName { get; set; }
        public string ClientName { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string EmployeeName { get; set; }
        public System.DateTime OrderDate { get; set; }
    }
}
